### ISSUE TITLE
(Un-)Localization

### ISSUE THREAD

**Issue by WKleinschmit** [lukesdm/image-comments#15]
The scale factor should be parsed using the invariant culture.
On my computer (Windows 7 x64 German) I have to enter 

```
/// <image url="$(ProjectDir)\img\About.png" scale="0,5" />
```

to scale the image to half its original size.
If I enter

```
/// <image url="$(ProjectDir)\img\About.png" scale="0.5" />
```

it is scaled to five times its original size.

**Comment by lukesdm** [comment]
Fixed in https://github.com/lukesdm/image-comments/pull/29
