### ISSUE TITLE
Upgrade image-comments to vs2015

### ISSUE THREAD

**Issue by Kirenenko** [lukesdm/image-comments#23]
Is there a possibility to upgrade that extension to make it work with visual studio 2015? I think it will be very usefull for the comunity. I've searched the web and it looks like there is nothing similar to image-comments for vs. Many thanks in advance!

**Comment by kentcb** [comment]
FWIW, I wanted the same thing a while back. I just downloaded the source, tweaked a couple of the VSIX properties and rebuilt. It installed in VS2015 fine.

[This tweet](https://twitter.com/kent_boogaart/status/627765490086055936) shows a capture of this add-in running in VS2015.

**Comment by Kirenenko** [comment]
Thank you Kent. I will try it.

**Comment by Kirenenko** [comment]
It works just adding my version to the extensions.vsixmanifest:

    <VisualStudio Version="14.0">
        <Edition>Enterprise</Edition>
    </VisualStudio>

Thanks again Kent.

**Comment by kentcb** [comment]
Yeah, that was it :)

No worries - glad you got it sorted. A shame this project seems to have languished because it's super useful when you need it.

**Comment by AKlaus** [comment]
I've got VS 2015 Enterprise and have the following error on launching the VSIX:

> This extension is not installable on any currently installed product

In the log it has a list of supported products:

- Microsoft.VisualStudio.Ultimate Version : [10.0]
- Microsoft.VisualStudio.Ultimate Version : [11.0]
- Microsoft.VisualStudio.Premium Version : [10.0]
- Microsoft.VisualStudio.Premium Version : [11.0]
- Microsoft.VisualStudio.Pro Version : [10.0]
- Microsoft.VisualStudio.Pro Version : [11.0]

It explains why mine `Microsoft Visual Studio Enterprise 2015` doesn't fit. But does anyone know how to install the plugin for VS2015?

**Comment by Kirenenko** [comment]
I think this is the same problem that I had. Just add the version to extensions.vsixmanifest file in the vsix package as I stated in my last message.

**Comment by lukesdm** [comment]
This repo has just been updated to support VS2019. Support for older versions may be available [here](https://github.com/TomSmartBishop/image-comments)
